// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/app/dao/internal"
)

// itemStockDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type itemStockDao struct {
	*internal.ItemStockDao
}

var (
	// ItemStock is globally public accessible object for table item_stock operations.
	ItemStock itemStockDao
)

func init() {
	ItemStock = itemStockDao{
		internal.NewItemStockDao(),
	}
}

// Fill with you ideas below.
