// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/app/dao/internal"
)

// promoDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type promoDao struct {
	*internal.PromoDao
}

var (
	// Promo is globally public accessible object for table promo operations.
	Promo promoDao
)

func init() {
	Promo = promoDao{
		internal.NewPromoDao(),
	}
}

// Fill with you ideas below.
