// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/app/dao/internal"
)

// sequenceInfoDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type sequenceInfoDao struct {
	*internal.SequenceInfoDao
}

var (
	// SequenceInfo is globally public accessible object for table sequence_info operations.
	SequenceInfo sequenceInfoDao
)

func init() {
	SequenceInfo = sequenceInfoDao{
		internal.NewSequenceInfoDao(),
	}
}

// Fill with you ideas below.
