// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/app/dao/internal"
	"gf-eshop/app/model"
	"github.com/gogf/gf/frame/g"
)

// userInfoDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type userInfoDao struct {
	*internal.UserInfoDao
}

var (
	// UserInfo is globally public accessible object for table user_info operations.
	UserInfo userInfoDao
)

func init() {
	UserInfo = userInfoDao{
		internal.NewUserInfoDao(),
	}
}

// Fill with you ideas below.
func (*userInfoDao) GetUserById(id int) (userInfo *model.UserInfo, err error){
	err = UserInfo.Where("id=?", id).Scan(&userInfo)
	if err != nil {
		g.Log().Errorf("根据ID获取用户失败，失败信息：%v", err.Error())
	}
	return
}
