// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/app/dao/internal"
)

// userPasswordDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type userPasswordDao struct {
	*internal.UserPasswordDao
}

var (
	// UserPassword is globally public accessible object for table user_password operations.
	UserPassword userPasswordDao
)

func init() {
	UserPassword = userPasswordDao{
		internal.NewUserPasswordDao(),
	}
}

// Fill with you ideas below.
