// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-eshop/app/dao/internal"
	"gf-eshop/app/model"
	"github.com/gogf/gf/frame/g"
)

// userPasswordDao is the manager for logic model data accessing and custom defined data operations functions management.
// You can define custom methods on it to extend its functionality as you wish.
type userPasswordDao struct {
	*internal.UserPasswordDao
}

var (
	// UserPassword is globally public accessible object for table user_password operations.
	UserPassword userPasswordDao
)

func init() {
	UserPassword = userPasswordDao{
		internal.NewUserPasswordDao(),
	}
}

// Fill with you ideas below.
func (*userPasswordDao) GetPasswordById(id int) (userPassword *model.UserPassword, err error){
	err = UserPassword.Where("user_id=?", id).Scan(&userPassword)
	if err != nil {
		g.Log().Errorf("根据ID获取用户密码，失败信息：%v", err.Error())
	}
	return
}