// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// OrderInfoDao is the manager for logic model data accessing and custom defined data operations functions management.
type OrderInfoDao struct {
	gmvc.M                  // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      orderInfoColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB           // DB is the raw underlying database management object.
	Table  string           // Table is the underlying table name of the DAO.
}

// OrderInfoColumns defines and stores column names for table order_info.
type orderInfoColumns struct {
	Id         string //
	UserId     string //
	ItemId     string //
	ItemPrice  string //
	Amount     string //
	OrderPrice string //
	PromoId    string //
}

// NewOrderInfoDao creates and returns a new DAO object for table data access.
func NewOrderInfoDao() *OrderInfoDao {
	columns := orderInfoColumns{
		Id:         "id",
		UserId:     "user_id",
		ItemId:     "item_id",
		ItemPrice:  "item_price",
		Amount:     "amount",
		OrderPrice: "order_price",
		PromoId:    "promo_id",
	}
	return &OrderInfoDao{
		C:     columns,
		M:     g.DB("default").Model("order_info").Safe(),
		DB:    g.DB("default"),
		Table: "order_info",
	}
}
