// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// PromoDao is the manager for logic model data accessing and custom defined data operations functions management.
type PromoDao struct {
	gmvc.M              // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      promoColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB       // DB is the raw underlying database management object.
	Table  string       // Table is the underlying table name of the DAO.
}

// PromoColumns defines and stores column names for table promo.
type promoColumns struct {
	Id             string //
	PromoName      string //
	StartDate      string //
	ItemId         string //
	PromoItemPrice string //
	EndDate        string //
}

// NewPromoDao creates and returns a new DAO object for table data access.
func NewPromoDao() *PromoDao {
	columns := promoColumns{
		Id:             "id",
		PromoName:      "promo_name",
		StartDate:      "start_date",
		ItemId:         "item_id",
		PromoItemPrice: "promo_item_price",
		EndDate:        "end_date",
	}
	return &PromoDao{
		C:     columns,
		M:     g.DB("default").Model("promo").Safe(),
		DB:    g.DB("default"),
		Table: "promo",
	}
}
