// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// SequenceInfoDao is the manager for logic model data accessing and custom defined data operations functions management.
type SequenceInfoDao struct {
	gmvc.M                     // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	C      sequenceInfoColumns // C is the short type for Columns, which contains all the column names of Table for convenient usage.
	DB     gdb.DB              // DB is the raw underlying database management object.
	Table  string              // Table is the underlying table name of the DAO.
}

// SequenceInfoColumns defines and stores column names for table sequence_info.
type sequenceInfoColumns struct {
	Name         string //
	CurrentValue string //
	Step         string //
}

// NewSequenceInfoDao creates and returns a new DAO object for table data access.
func NewSequenceInfoDao() *SequenceInfoDao {
	columns := sequenceInfoColumns{
		Name:         "name",
		CurrentValue: "current_value",
		Step:         "step",
	}
	return &SequenceInfoDao{
		C:     columns,
		M:     g.DB("default").Model("sequence_info").Safe(),
		DB:    g.DB("default"),
		Table: "sequence_info",
	}
}
